### PR TITLE
Update LootValue Mod - Add Coop trader filter

### PR DESCRIPTION
**Pull request by NizZ8**
-Filter out Coop traders by default for quickselling
-Updated MasterList.json to PortVersion 1.1.0

### CODE REVIEW

**Comment by nimbuldev** [comment]
thank god

**Comment by Lacyway** [comment]
Is this one still valid?

**Comment by NizZ8** [comment]
Yes this one is still valid, it didn't make it into the other update from earlier... Can update the PortVersion if needed, lmk

**Comment by Lacyway** [comment]
Does it work on the latest SIT version? If so update the MasterList file and I'll merge. Thanks and sorry.

**Comment by NizZ8** [comment]
Yep this works on the latest SIT version, updated the PortVersion to 1.2.0.

**Pull request merged**
