### PR TITLE
add SPTQuestingBots-SIT

### PR DESCRIPTION
**Pull request by GauxCodes**
Ports SPTQuestingBots 0.3.4 to SIT.

- There are still some (minor?) issues I am still fixing 
- I think the mod in it's current state already adds gameplay value to SIT
- Not yet tested with multiple clients connected
- Modifications may be required in build config `.csproj`

### CODE REVIEW

**Comment by GauxCodes** [comment]
Open todos on my side:

QuestingBotsPlugin.cs - Add requirements for SIT as dependency

BotMonitor.cs - Something not quite right in `ShouldCheckForLoot`. Clean up big if statement.

BotHiveMindMonitor.cs - Commented out all calls to `UpdateValueForBot`, `GetValueForBot` (for now), seem to be broken.

BotGenerator.cs - Hardcoded value used to calculate if PMCs should get spawned to 95%. As far as I can tell, the repercussions of this are that PMCs will keep spawning throughout the raid at the same rate as if 95% of the raid time is remaining, and will keep respawning once some are killed.

BotJobAssignmentFactory.cs - Comment out logic to look for extract

**Comment by Lacyway** [comment]
I'm on vacation, will take a look when I get home. Or if @nimbuldev can verify that it works I can approve the PR.

**Comment by shibdib** [comment]
"BotJobAssignmentFactory.cs - Comment out logic to look for extract."

The 2.1.7 version of SAIN PR adds support for external apps to enter the SAIN extract layer.

**Comment by nimbuldev** [comment]
https://youtu.be/QcfDUA-fWFM?si=6lFSy1atRuRTasVX Similar experiences from @shibdib and @NizZ8 

We agree it seems to need more time to cook. Could be a core issue with our waypoints seeing as @shibdib says it's very reminiscent of SAIN's look for extract bug.

**Comment by GauxCodes** [comment]
Thanks for checking!

I suspect we have a different server setup. I currently have both scavs and pmcs enabled for questing in the server config:

`Server/user/mods/DanW-SPTQuestingBots/config.json`
```
...
 "allowed_bot_types_for_questing": {
              "scav": true,
              "pmc": true,
              "boss": false
},
```

I find that way more often than not, bots are finding a path to their objective on my setup. Just to be sure, I'll list the (relevant) mods in server and client that I have setup:

```
Server mods:
- SITCoop
- zzDrakiaXYZ-Waypoints
- DanW-SPTQuestingBots
- zSolarint-SAIN-ServerMod

Client mods:
- custom, navmesh setup
- (Ported)SAIN
- StayInTarkov.dll
- (Ported)LootingBots
```

I added some logs to check the success rate for finding a path with this setup:

```
[Warning:DanW-QuestingBots] Waiting for spawnInitialPMCsAtSpawnPoint until next frame...done. (Cycle times: 42, 43, 33, 44, 78, 40, 0, Total time: 1474)
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 1
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 1
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 1
[Warning:DanW-QuestingBots] Bot PudgeNubbins (Name: Bot7, Level: 11) cannot find a path to Step #1 for objective Zone extraction_zone_zibbo in quest Golden Swag
[Info   :DanW-QuestingBots] Bot PudgeNubbins (Name: Bot7, Level: 11) has failed Step #1 for objective Zone extraction_zone_zibbo in quest Golden Swag
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.8888889
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9090909
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9166667
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9230769
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9285714
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9333333
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9375
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9411765
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9444444
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9473684
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.95
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.952381
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9545454
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9565217
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9583333
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.96
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9615384
[Info   :RoamingLayer] Added roaming to Bot10
[Info   :DanW-QuestingBots] Initial spawn type for bot DjLang (Name: Bot10, Level: 19): sptUsec
[Info   :DanW-QuestingBots] DjLang (Name: Bot10, Level: 19) is a PMC.
[Info   :DanW-QuestingBots] Setting objective for PMC DjLang (Name: Bot10, Level: 19) (Brain type: Assault)...
[Info   :DanW-QuestingBots] Bot DjLang (Name: Bot10, Level: 19) is now doing Step #1 for objective Zone vremyan_case in quest The Extortionist
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.962963
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9642857
[Info   :DanW-QuestingBots] DjLang (Name: Bot10, Level: 19) is swtiching from Undefined to GoToObjective
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9655172
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9666666
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9677419
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.96875
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.969697
[Warning:DanW-QuestingBots] Bot DjLang (Name: Bot10, Level: 19) cannot find a path to Step #1 for objective Zone vremyan_case in quest The Extortionist
[Info   :DanW-QuestingBots] Bot DjLang (Name: Bot10, Level: 19) has failed Step #1 for objective Zone vremyan_case in quest The Extortionist
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9428571
[Info   :RoamingLayer] Added roaming to Bot12
[Info   :DanW-QuestingBots] Initial spawn type for bot kmyuhkyuk (Name: Bot12, Level: 7): sptUsec
[Info   :DanW-QuestingBots] kmyuhkyuk (Name: Bot12, Level: 7) is a PMC.
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9444444
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9459459
[Info   :DanW-QuestingBots] Setting objective for PMC kmyuhkyuk (Name: Bot12, Level: 7) (Brain type: Assault)...
[Info   :DanW-QuestingBots] Bot kmyuhkyuk (Name: Bot12, Level: 7) is now doing Step #1 for objective Spawn Point (-273.5, 1.0, -72.1) in quest Spawn Points
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9473684
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.948718
[Info   :DanW-QuestingBots] kmyuhkyuk (Name: Bot12, Level: 7) is swtiching from Undefined to GoToObjective
[Info   :RoamingLayer] Added roaming to Bot11
[Info   :DanW-QuestingBots] Initial spawn type for bot Snofielf (Name: Bot11, Level: 8): sptUsec
[Info   :DanW-QuestingBots] Snofielf (Name: Bot11, Level: 8) is a PMC.
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.95
[Info   :RoamingLayer] Added roaming to Bot13
[Info   :DanW-QuestingBots] Initial spawn type for bot Conqueror_Alex (Name: Bot13, Level: 1): sptBear
[Info   :DanW-QuestingBots] Conqueror_Alex (Name: Bot13, Level: 1) is a PMC.
[Info   :DanW-QuestingBots] Setting objective for PMC Snofielf (Name: Bot11, Level: 8) (Brain type: Assault)...
[Info   :DanW-QuestingBots] Bot Snofielf (Name: Bot11, Level: 8) is now doing Step #1 for objective Spawn Point (-134.2, -1.4, 38.1) in quest Spawn Points
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9512195
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.952381
[Info   :DanW-QuestingBots] Snofielf (Name: Bot11, Level: 8) is swtiching from Undefined to GoToObjective
[Info   :DanW-QuestingBots] Setting objective for PMC Conqueror_Alex (Name: Bot13, Level: 1) (Brain type: Assault)...
[Info   :DanW-QuestingBots] Bot Conqueror_Alex (Name: Bot13, Level: 1) is now doing Step #1 for objective Spawn Point (571.6, 11.4, 145.3) in quest Spawn Points
[Info   :DanW-QuestingBots] Bot pathfinder success rate: 0.9534883
....
```

**Comment by shibdib** [comment]
My super messy PR I just re-enabled extracts as I didn't feel like disabling something in a port that sorta sometimes works was the move, Instead I just set them to off by default and added some flavor text to the UI about them being buggy. So it should be safe to integrate.

But yes, I think the pathing issues in both of these mods point towards SIT being the culprit. Whether it's the way waypoints is baked in or something else.

**Comment by shibdib** [comment]
Confirming this works well with the aforementioned waypoints integration changes. But seeing how the next SIT release will be 0.14 and will not include waypoints/brain baked in, we'll probably be best to wait until that's out and redo the port (along with all the other AI ones) to support standalone versions of those mods.

**Comment by shibdib** [comment]
Currently have a branch https://github.com/shibdib/SIT-Mod-Ports/tree/QuestingBots-42820 that has a few changes from the Gaux version (all credit to him for the initial port) that is released for testing at https://discord.com/channels/1175114933713776690/1195461195679944844

It requires a SIT dll change so probably not good for a merge here until .14, but is letting us work out kinks.

**Comment by mihaicm93** [comment]
Would be more than happy to have this ported, I hope the efforts to improve mod compatibility will make it easier to get this ported now that waypoints and big brain have been removed. Looking forward to the PR if you have the time to look into it for the new version

**Comment by shibdib** [comment]
@GauxCodes would have to do it, I haven't opened any version of Tarkov since leaving the discord.

**Comment by mihaicm93** [comment]
> @GauxCodes would have to do it, I haven't opened any version of Tarkov since leaving the discord.

If he wants and has time, also I'm glad to see that you are ok @shibdib <3

**Pull request closed without merging**
