### PR TITLE
Add SamSwat's INCREASED FOV plugin

### PR DESCRIPTION
**Pull request by nimbuldev**
Adds SamSwat's Increased FOV plugin

### CODE REVIEW

**Comment by nimbuldev** [comment]
Oops, my commit names kind of suck now that I look at them. :)

**Review by Lacyway — CHANGES_REQUESTED** [review]
A lot of files require Aki.Reflection still. Change to StayInTarkov.dll. 

Same with PrePatcher file, does that one work?

**Comment by nimbuldev** [comment]
Removed all references to Aki.Reflection. 👍🏻

**Comment by Lacyway** [comment]
Fixed and added.

**Review by Lacyway — APPROVED** [review]

**Pull request merged**
